"""
Unified architecture comparison for RV regression.

Fair-comparison features:
- Explicit GPU control (--device auto|cuda|cpu); cuDNN benchmark + TF32 on GPU.
- Multi-seed evaluation (--seeds / --n-seeds) with mean +- std aggregation.
- Clean train/val/test split within each fold via val_frac (--val-frac).
  Inner val is used for early stopping; the original fold-val becomes a
  held-out TEST set used only for reported metrics.
- Matched-param mode (--match-params) that binary-searches d_model per
  architecture so that all architectures have comparable parameter budgets.
- Lightweight per-architecture random-search HPO (--hpo-trials) over
  {lr, dropout, weight_decay}, selected by mean inner-val loss (no leakage).
- Feature-set selection (--feature-set recommended|full) to surface the
  bias coming from a feature list generated by a non-transformer model.
- Cost/throughput measurement per architecture (latency, peak memory).
- Baselines (persistence / historical_mean / linear / lightgbm / lstm) are
  evaluated on the same folds and merged into the same CSV.

Outputs (under transformer/output/experiments/):
- architecture_comparison.csv           : one row per model_type with
  mean/std metrics and cost columns.
- architecture_comparison.signature.json: hash of run configuration.
- architecture_hpo_trials.csv           : per-trial HPO log (when enabled).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import time

import numpy as np
import pandas as pd


def _append_text(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fair architecture comparison (transformers + baselines) for multi-horizon RV regression."
    )
    parser.add_argument("--use-cache", action="store_true")
    parser.add_argument("--quick", action="store_true", help="Reduce epochs/folds for a smoke run.")
    parser.add_argument("--max-epochs", type=int, default=None)
    parser.add_argument("--n-splits", type=int, default=None)
    parser.add_argument(
        "--device",
        choices=["auto", "cuda", "cpu"],
        default="auto",
        help="'cuda' fails if GPU is unavailable; 'cpu' forces CPU even if CUDA is present.",
    )
    parser.add_argument(
        "--seeds",
        type=str,
        default=None,
        help="Comma-separated seeds (overrides --n-seeds), e.g. '42,123,2024'.",
    )
    parser.add_argument(
        "--n-seeds",
        type=int,
        default=None,
        help="Generate N seeds starting from train.seed (ignored if --seeds provided).",
    )
    parser.add_argument(
        "--architectures",
        type=str,
        default="patch_encoder,decoder_only,vanilla_enc_dec,patch_decoder",
        help="Comma-separated list of transformer model_type values.",
    )
    parser.add_argument(
        "--val-frac",
        type=float,
        default=0.0,
        help="Fraction of each fold's X_train used as inner-val for early stopping. "
             "0.0 = standalone-parity mode (val = test).",
    )
    parser.add_argument(
        "--match-params",
        type=str,
        default="none",
        help="Parameter-budget matching mode: 'none' | 'auto' | <int>. "
             "'auto' uses patch_encoder @ d_model=64 as reference.",
    )
    parser.add_argument(
        "--feature-set",
        choices=["recommended", "full"],
        default="recommended",
        help="'recommended' uses feature_selection/output/recommended_features.csv, "
             "'full' uses every numeric non-target column from the dataset.",
    )
    parser.add_argument(
        "--hpo-trials",
        type=int,
        default=1,
        help="Random-search trials per architecture. 1 = no HPO (defaults).",
    )
    parser.add_argument(
        "--hpo-epoch-frac",
        type=float,
        default=0.33,
        help="Fraction of --max-epochs used for each HPO trial (bounded by >= 3).",
    )
    parser.add_argument(
        "--skip-baselines",
        action="store_true",
        help="Do not include baseline models in the unified comparison table.",
    )
    parser.add_argument(
        "--skip-lstm-baseline",
        action="store_true",
        help="Skip the slow LSTM baseline (useful for quick sanity checks).",
    )
    parser.add_argument(
        "--skip-transformers",
        action="store_true",
        help="Only evaluate baselines (for quick sanity checks).",
    )
    parser.add_argument(
        "--dm-ref",
        type=str,
        default="patch_encoder",
        help="Model type used as reference for DM/bootstraps (default: patch_encoder).",
    )
    parser.add_argument(
        "--dm-block-size",
        type=int,
        default=48,
        help="Block size (bars) for moving-block bootstrap (default: 48).",
    )
    parser.add_argument(
        "--dm-n-boot",
        type=int,
        default=2000,
        help="Number of bootstrap replications for CI (default: 2000; reduced under --quick).",
    )
    parser.add_argument(
        "--cost-batch-size",
        type=int,
        default=64,
        help="Batch size used for inference cost/throughput measurement.",
    )
    parser.add_argument(
        "--cost-iters",
        type=int,
        default=50,
        help="Number of timed inference iterations for cost measurement.",
    )
    return parser.parse_args()


def _configure_device_env(device: str) -> None:
    if device == "cpu":
        os.environ["CUDA_VISIBLE_DEVICES"] = ""


def _enable_gpu_perf_flags(torch_module) -> None:
    if not torch_module.cuda.is_available():
        return
    torch_module.backends.cudnn.benchmark = True
    try:
        torch_module.backends.cuda.matmul.allow_tf32 = True
        torch_module.backends.cudnn.allow_tf32 = True
    except Exception:
        pass


def _resolve_seeds(args: argparse.Namespace, base_seed: int) -> list[int]:
    if args.seeds:
        seeds = [int(s.strip()) for s in args.seeds.split(",") if s.strip()]
        if not seeds:
            raise ValueError("--seeds is empty after parsing.")
        return seeds
    if args.n_seeds is not None and args.n_seeds > 0:
        return [int(base_seed) + i for i in range(args.n_seeds)]
    return [int(base_seed)]


def _config_signature(payload: dict) -> str:
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False, default=str).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()[:16]


def _progress(step: int, total: int, message: str) -> None:
    pct = int((step / max(total, 1)) * 100)
    now = time.strftime("%H:%M:%S")
    print(f"[{now}] [{step}/{total}] ({pct:>3}%) {message}")


def _aggregate_metric(per_run_metrics: list[dict], key: str) -> tuple[float, float]:
    import numpy as np
    vals = [float(m[key]) for m in per_run_metrics if key in m and m[key] is not None]
    vals = [v for v in vals if np.isfinite(v)]
    if not vals:
        return float("nan"), float("nan")
    mean = float(np.mean(vals))
    std = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
    return mean, std


def _count_model_params(
    model_type: str,
    input_dim: int,
    seq_len: int,
    patch_size: int,
    d_model: int,
    n_heads: int,
    n_enc_layers: int,
    n_dec_layers: int,
    d_ff: int,
    n_horizons: int,
    dropout: float,
) -> int:
    from transformer.model import build_model
    m = build_model(
        model_type=model_type,
        input_dim=input_dim,
        seq_len=seq_len,
        patch_size=patch_size,
        d_model=d_model,
        n_heads=n_heads,
        n_layers=n_enc_layers,
        d_ff=d_ff,
        dropout=dropout,
        n_horizons=n_horizons,
        n_enc_layers=n_enc_layers,
        n_dec_layers=n_dec_layers,
    )
    n = sum(p.numel() for p in m.parameters())
    del m
    return int(n)


def _find_dmodel_for_target_params(
    target_params: int,
    *,
    model_type: str,
    input_dim: int,
    seq_len: int,
    patch_size: int,
    n_heads: int,
    n_enc_layers: int,
    n_dec_layers: int,
    n_horizons: int,
    dropout: float,
    d_model_min: int = 16,
    d_model_max: int = 512,
) -> tuple[int, int]:
    """Return (best_d_model, param_count) minimizing |params - target|."""
    best_d = d_model_min
    best_diff = float("inf")
    best_n = 0
    # d_model must be divisible by n_heads; step by n_heads.
    prev_n = -1
    increased = False
    for d in range(max(d_model_min, n_heads), d_model_max + 1, n_heads):
        d_ff = 4 * d
        n = _count_model_params(
            model_type=model_type,
            input_dim=input_dim,
            seq_len=seq_len,
            patch_size=patch_size,
            d_model=d,
            n_heads=n_heads,
            n_enc_layers=n_enc_layers,
            n_dec_layers=n_dec_layers,
            d_ff=d_ff,
            n_horizons=n_horizons,
            dropout=dropout,
        )
        diff = abs(n - target_params)
        if diff < best_diff:
            best_diff = diff
            best_d = d
            best_n = n
        # Near-monotonic: once we overshoot target by a lot, stop.
        if prev_n >= 0 and n > target_params:
            increased = True
        prev_n = n
        if increased and n > 2 * target_params:
            break
    return best_d, best_n


def _measure_cost(
    *,
    model_type: str,
    device,
    input_dim: int,
    seq_len: int,
    patch_size: int,
    d_model: int,
    n_heads: int,
    n_enc_layers: int,
    n_dec_layers: int,
    d_ff: int,
    n_horizons: int,
    dropout: float,
    batch_size: int = 64,
    n_iter: int = 50,
) -> dict:
    import torch
    from transformer.dataset import N_HAR_CONTEXT
    from transformer.model import build_model

    use_har = str(model_type).lower() in {"patch_encoder", "encoder_only"}
    model = build_model(
        model_type=model_type,
        input_dim=input_dim,
        seq_len=seq_len,
        patch_size=patch_size,
        d_model=d_model,
        n_heads=n_heads,
        n_layers=n_enc_layers,
        d_ff=d_ff,
        dropout=dropout,
        n_horizons=n_horizons,
        n_enc_layers=n_enc_layers,
        n_dec_layers=n_dec_layers,
    ).to(device).eval()

    x = torch.randn(batch_size, seq_len, input_dim, device=device)
    har = torch.randn(batch_size, N_HAR_CONTEXT, device=device) if use_har else None

    # Warm-up
    with torch.no_grad():
        for _ in range(5):
            _ = model(x, har) if use_har else model(x)
    if device.type == "cuda":
        torch.cuda.synchronize()
        torch.cuda.reset_peak_memory_stats()

    t0 = time.perf_counter()
    with torch.no_grad():
        for _ in range(n_iter):
            _ = model(x, har) if use_har else model(x)
    if device.type == "cuda":
        torch.cuda.synchronize()
    dt = time.perf_counter() - t0
    latency_ms_batch = (dt / n_iter) * 1000.0
    throughput = (n_iter * batch_size) / dt if dt > 0 else float("nan")
    peak_mb = (
        torch.cuda.max_memory_allocated() / (1024 * 1024)
        if device.type == "cuda"
        else float("nan")
    )
    del model
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return {
        "latency_ms_batch": float(latency_ms_batch),
        "latency_ms_sample": float(latency_ms_batch / max(batch_size, 1)),
        "throughput_samples_per_sec": float(throughput),
        "peak_mem_mb": float(peak_mb),
        "cost_batch_size": int(batch_size),
    }


def _hpo_random_search(
    *,
    args: argparse.Namespace,
    model_type: str,
    model_cfg,
    train_cfg,
    data_path: str,
    feature_columns: list[str],
    val_frac: float,
    seed: int,
    n_trials: int,
) -> tuple[dict, list[dict]]:
    """Return (best_hparams, trial_logs). Select by mean inner-val loss."""
    import random
    from dataclasses import replace
    from transformer.train import train_walk_forward_regression

    hpo_epochs = max(3, int(round(train_cfg.max_epochs * float(args.hpo_epoch_frac))))
    rng = random.Random(int(seed))
    trial_logs: list[dict] = []
    best_hp: dict | None = None
    best_loss = float("inf")
    for t in range(n_trials):
        lr = 10 ** rng.uniform(-5, -3)
        dropout = rng.choice([0.1, 0.15, 0.2, 0.25, 0.3])
        weight_decay = 10 ** rng.uniform(-6, -3)
        m_cfg = replace(model_cfg, dropout=float(dropout))
        t_cfg = replace(
            train_cfg,
            lr=float(lr),
            weight_decay=float(weight_decay),
            max_epochs=int(hpo_epochs),
            seed=int(seed),
        )
        started = time.perf_counter()
        try:
            result = train_walk_forward_regression(
                data_path=data_path,
                features_path="",
                model_cfg=m_cfg,
                train_cfg=t_cfg,
                save_models=False,
                model_prefix=f"hpo_{model_type}_t{t}",
                run_name=f"hpo_{model_type}_t{t}",
                val_frac=val_frac,
                feature_columns=feature_columns,
            )
        except Exception as exc:
            trial_logs.append({
                "model_type": model_type, "trial": t, "lr": lr,
                "dropout": float(dropout), "weight_decay": weight_decay,
                "mean_val_loss": float("inf"), "elapsed_sec": 0.0, "error": str(exc),
            })
            continue
        elapsed = time.perf_counter() - started
        fold_val_losses = [float(m.get("val_loss", float("inf"))) for m in result["metrics_per_fold"]]
        mean_vl = float(sum(fold_val_losses) / max(len(fold_val_losses), 1)) if fold_val_losses else float("inf")
        trial_logs.append({
            "model_type": model_type, "trial": t, "lr": float(lr),
            "dropout": float(dropout), "weight_decay": float(weight_decay),
            "mean_val_loss": mean_vl, "elapsed_sec": round(elapsed, 2),
        })
        if mean_vl < best_loss:
            best_loss = mean_vl
            best_hp = {"lr": float(lr), "dropout": float(dropout), "weight_decay": float(weight_decay)}
        print(
            f"  [HPO {model_type} t={t+1}/{n_trials}] "
            f"lr={lr:.2e} do={dropout:.2f} wd={weight_decay:.2e} "
            f"mean_val_loss={mean_vl:.6f} elapsed={elapsed:.1f}s"
        )
    if best_hp is None:
        best_hp = {"lr": train_cfg.lr, "dropout": model_cfg.dropout, "weight_decay": train_cfg.weight_decay}
    return best_hp, trial_logs


def _run_baselines_block(
    *,
    data_path: str,
    n_splits: int,
    target_columns: tuple[str, ...],
    metric_keys: tuple[str, ...],
    project_root: str,
) -> list[dict]:
    import numpy as np

    baselines_dir = os.path.join(project_root, "baselines")
    if baselines_dir not in sys.path:
        sys.path.insert(0, baselines_dir)

    from historical_mean_baseline import run as run_hist  # type: ignore
    from har_rv_baseline import run as run_har_rv  # type: ignore
    from har_rv_j_baseline import run as run_har_rv_j  # type: ignore
    from lightgbm_baseline import run as run_lgbm  # type: ignore
    from linear_regression_baseline import run as run_lin  # type: ignore
    from lstm_baseline import run as run_lstm  # type: ignore
    from persistence_baseline import run as run_pers  # type: ignore

    specs = [
        ("baseline:persistence", run_pers),
        ("baseline:historical_mean", run_hist),
        ("baseline:har_rv", run_har_rv),
        ("baseline:har_rv_j", run_har_rv_j),
        ("baseline:linear_ridge", run_lin),
        ("baseline:lightgbm", run_lgbm),
    ]
    if os.environ.get("SKIP_LSTM_BASELINE", "").strip() not in {"1", "true", "True"}:
        specs.append(("baseline:lstm", run_lstm))
    rows: list[dict] = []
    for name, fn in specs:
        print("\n" + "-" * 90)
        print(f"[BASELINE] {name} | folds={n_splits}")
        print("-" * 90)
        t0 = time.perf_counter()
        try:
            out = fn(
                data_path=data_path,
                n_splits=n_splits,
                target_columns=target_columns,
                return_predictions=False,
            )
        except Exception as exc:
            elapsed = time.perf_counter() - t0
            print(f"  [BASELINE] {name} failed: {exc}")
            row: dict = {
                "model_type": name, "n_params": float("nan"),
                "n_seeds": 1, "n_folds": n_splits, "n_samples": 0,
                "device": "cpu", "elapsed_sec": round(elapsed, 2),
                "latency_ms_batch": float("nan"), "latency_ms_sample": float("nan"),
                "throughput_samples_per_sec": float("nan"), "peak_mem_mb": float("nan"),
                "cost_batch_size": float("nan"), "error": str(exc),
            }
            for k in metric_keys:
                row[k] = float("nan")
                row[k.replace("_mean", "_std")] = float("nan")
            row["model_config"] = ""
            rows.append(row)
            continue
        # Backward-compatible: baselines may return list[dict] or a dict bundle.
        if isinstance(out, dict) and "metrics_per_fold" in out:
            fold_metrics = out["metrics_per_fold"]
        else:
            fold_metrics = out
        elapsed = time.perf_counter() - t0
        row = {
            "model_type": name, "n_params": float("nan"),
            "n_seeds": 1, "n_folds": n_splits, "n_samples": len(fold_metrics),
            "device": "cpu", "elapsed_sec": round(elapsed, 2),
            "latency_ms_batch": float("nan"), "latency_ms_sample": float("nan"),
            "throughput_samples_per_sec": float("nan"), "peak_mem_mb": float("nan"),
            "cost_batch_size": float("nan"),
        }
        for k in metric_keys:
            mean, std = _aggregate_metric(fold_metrics, k)
            row[k] = mean
            row[k.replace("_mean", "_std")] = std
        row["model_config"] = ""
        rows.append(row)
        print(
            f"[BASELINE DONE] {name}: mse={row['mse_mean']:.6f} "
            f"qlike={row['qlike_mean']:.6f} r2={row['r2_mean']:.4f} elapsed={row['elapsed_sec']}s"
        )
    return rows


def _extract_loss_streams(pred_df: pd.DataFrame, target_columns: tuple[str, ...]) -> dict[str, np.ndarray]:
    """Return per-horizon and aggregate loss streams from a pred_df."""
    from scripts.stats_tests import qlike_series  # local import to avoid cycles

    out: dict[str, np.ndarray] = {}
    loss_parts: list[np.ndarray] = []
    for col in target_columns:
        a = pred_df[f"actual_{col}"].to_numpy(dtype=float)
        p = pred_df[f"pred_{col}"].to_numpy(dtype=float)
        ls = qlike_series(a, p)
        out[col] = ls
        loss_parts.append(ls.reshape(-1, 1))
    if loss_parts:
        out["agg"] = np.mean(np.concatenate(loss_parts, axis=1), axis=1)
    else:
        out["agg"] = np.array([], dtype=float)
    return out


def _compute_dm_and_bootstrap(
    *,
    pred_m0: pd.DataFrame,
    pred_m1: pd.DataFrame,
    target_columns: tuple[str, ...],
    block_size: int,
    n_boot: int,
    hac_lags: int | None,
    seed: int = 42,
) -> dict[str, float]:
    """Compute DM p-values and bootstrap CI for mean(loss_m0 - loss_m1)."""
    from scripts.stats_tests import dm_test, moving_block_bootstrap_mean_ci

    # Align on timestamps to be safe.
    if "ts" in pred_m0.columns and "ts" in pred_m1.columns:
        a = pred_m0.copy()
        b = pred_m1.copy()
        a["ts"] = pd.to_datetime(a["ts"], utc=True, errors="coerce")
        b["ts"] = pd.to_datetime(b["ts"], utc=True, errors="coerce")
        merged = a.merge(b, on="ts", how="inner", suffixes=("_m0", "_m1"))
        # Rebuild aligned frames.
        pred0 = pd.DataFrame({"ts": merged["ts"]})
        pred1 = pd.DataFrame({"ts": merged["ts"]})
        for col in target_columns:
            pred0[f"actual_{col}"] = merged[f"actual_{col}_m0"]
            pred0[f"pred_{col}"] = merged[f"pred_{col}_m0"]
            pred1[f"actual_{col}"] = merged[f"actual_{col}_m1"]
            pred1[f"pred_{col}"] = merged[f"pred_{col}_m1"]
    else:
        pred0 = pred_m0
        pred1 = pred_m1

    loss0 = _extract_loss_streams(pred0, target_columns)
    loss1 = _extract_loss_streams(pred1, target_columns)

    rng = np.random.default_rng(int(seed))
    out: dict[str, float] = {}
    keys = list(target_columns) + ["agg"]
    for k in keys:
        dm = dm_test(loss0[k], loss1[k], hac_lags=hac_lags, alternative="two-sided")
        d = (loss0[k] - loss1[k]).astype(float)
        mean_d, lo, hi = moving_block_bootstrap_mean_ci(
            d,
            block_size=int(block_size),
            n_boot=int(n_boot),
            alpha=0.05,
            rng=rng,
        )
        suffix = "agg" if k == "agg" else k
        out[f"dm_stat_{suffix}"] = float(dm.dm_stat)
        out[f"dm_p_{suffix}"] = float(dm.p_value)
        out[f"diff_mean_{suffix}"] = float(mean_d)
        out[f"diff_ci_lo_{suffix}"] = float(lo)
        out[f"diff_ci_hi_{suffix}"] = float(hi)
        out[f"dm_n_{suffix}"] = float(dm.n)
        out[f"dm_hac_lags_{suffix}"] = float(dm.hac_lags)
    return out


def _resolve_feature_list(
    feature_set: str,
    data_path: str,
    features_path: str,
    project_root: str,
) -> list[str]:
    """Resolve feature list depending on --feature-set."""
    baselines_dir = os.path.join(project_root, "baselines")
    if baselines_dir not in sys.path:
        sys.path.insert(0, baselines_dir)
    from utils import get_feature_columns, load_dataset  # type: ignore

    df = load_dataset(data_path)
    if feature_set == "full":
        return list(get_feature_columns(df))

    from transformer.dataset import load_recommended_features, resolve_features
    # Symbol-specific recommended_features.csv may be missing; fall back to global output.
    fp = features_path
    if fp and not os.path.exists(fp):
        alt = os.path.join(project_root, "feature_selection", "output", "recommended_features.csv")
        if os.path.exists(alt):
            fp = alt
    rec = load_recommended_features(fp)
    return list(resolve_features(df, rec))


def main() -> None:  # noqa: C901
    started = time.time()
    args = parse_args()
    _configure_device_env(args.device)
    os.environ["SKIP_LSTM_BASELINE"] = "1" if args.skip_lstm_baseline else "0"

    from dataclasses import asdict, replace

    import numpy as np
    import pandas as pd
    import torch

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    from transformer.config import AppConfig, ModelConfig, ensure_output_dirs
    from transformer.train import train_walk_forward_regression

    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError(
            "--device cuda requested, but torch.cuda.is_available() is False. "
            "Install a CUDA build of torch or use --device auto/cpu."
        )
    use_cuda = args.device in {"auto", "cuda"} and torch.cuda.is_available()
    device = torch.device("cuda" if use_cuda else "cpu")
    if device.type == "cuda":
        _enable_gpu_perf_flags(torch)
        gpu_name = torch.cuda.get_device_name(0)
        total_mem_gb = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)
        print(
            f"[DEVICE] cuda | gpu={gpu_name} | mem={total_mem_gb:.1f}GB | "
            f"torch.cuda={torch.version.cuda} | cudnn_benchmark=on | tf32=on"
        )
    else:
        print("[DEVICE] cpu (CUDA unavailable or forced via --device cpu)")

    cfg = AppConfig()
    if args.quick:
        cfg = AppConfig(
            data_path=cfg.data_path,
            features_path=cfg.features_path,
            model=cfg.model,
            train=replace(cfg.train, max_epochs=3, n_splits=2, patience=2),
        )
    if args.max_epochs is not None or args.n_splits is not None:
        cfg = AppConfig(
            data_path=cfg.data_path,
            features_path=cfg.features_path,
            model=cfg.model,
            train=replace(
                cfg.train,
                max_epochs=args.max_epochs if args.max_epochs is not None else cfg.train.max_epochs,
                n_splits=args.n_splits if args.n_splits is not None else cfg.train.n_splits,
            ),
        )

    seeds = _resolve_seeds(args, cfg.train.seed)
    architectures = [a.strip() for a in args.architectures.split(",") if a.strip()]
    if not architectures and not args.skip_transformers:
        raise ValueError("No architectures requested and --skip-transformers is not set.")

    feature_columns = _resolve_feature_list(
        feature_set=args.feature_set,
        data_path=cfg.data_path,
        features_path=cfg.features_path,
        project_root=project_root,
    )
    input_dim = len(feature_columns)
    print(
        f"[DATA] features_set={args.feature_set} | features={input_dim} | "
        f"horizons={len(cfg.train.target_columns)} | seeds={seeds} | val_frac={args.val_frac}"
    )
    if float(args.val_frac) != 0.0:
        print(
            "[WARN] val_frac != 0.0 enables inner-val split. "
            "Metrics may differ from standalone run_transformer.py mode."
        )

    # Resolve match-params target
    match_mode = str(args.match_params).strip().lower()
    target_params: int | None = None
    if match_mode == "auto":
        target_params = _count_model_params(
            model_type="patch_encoder",
            input_dim=input_dim,
            seq_len=240, patch_size=12, d_model=64, n_heads=4,
            n_enc_layers=3, n_dec_layers=2, d_ff=256,
            n_horizons=len(cfg.train.target_columns), dropout=0.2,
        )
        print(f"[MATCH-PARAMS] mode=auto | target_params={target_params:,} (patch_encoder @ d_model=64)")
    elif match_mode != "none":
        try:
            target_params = int(match_mode.replace("_", ""))
            print(f"[MATCH-PARAMS] mode=fixed | target_params={target_params:,}")
        except ValueError as exc:
            raise ValueError(f"--match-params must be 'none', 'auto', or an integer; got {args.match_params!r}") from exc
    else:
        print("[MATCH-PARAMS] disabled — each arch uses default d_model=64")

    ensure_output_dirs()
    out_dir = os.path.join(project_root, "transformer", "output", "experiments")
    os.makedirs(out_dir, exist_ok=True)
    out_csv = os.path.join(out_dir, "architecture_comparison.csv")
    sig_path = os.path.join(out_dir, "architecture_comparison.signature.json")
    hpo_csv = os.path.join(out_dir, "architecture_hpo_trials.csv")
    symbol = os.environ.get("SYMBOL", "BTCUSDT").strip().upper() or "BTCUSDT"
    dm_log_path = os.path.join(project_root, "logs", f"dm_bootstrap_{symbol}.txt")

    signature_payload = {
        "architectures": architectures,
        "seeds": seeds,
        "max_epochs": cfg.train.max_epochs,
        "n_splits": cfg.train.n_splits,
        "patience": cfg.train.patience,
        "data_path": cfg.data_path,
        "features_path": cfg.features_path if args.feature_set == "recommended" else "__full__",
        "feature_count": input_dim,
        "target_columns": list(cfg.train.target_columns),
        "device": device.type,
        "val_frac": float(args.val_frac),
        "match_params": target_params,
        "hpo_trials": int(args.hpo_trials),
        "hpo_epoch_frac": float(args.hpo_epoch_frac),
        "skip_baselines": bool(args.skip_baselines),
        "skip_transformers": bool(args.skip_transformers),
    }
    signature = _config_signature(signature_payload)
    _progress(1, 3, f"Initialized (signature={signature})")

    if args.use_cache and os.path.exists(out_csv) and os.path.exists(sig_path):
        try:
            with open(sig_path, "r", encoding="utf-8") as f:
                cached_sig = json.load(f).get("signature")
        except Exception:
            cached_sig = None
        if cached_sig == signature:
            cached = pd.read_csv(out_csv)
            _progress(2, 3, "Loaded cached architecture comparison")
            print(f"Using cached results: {out_csv}")
            print(cached.to_string(index=False))
            _progress(3, 3, f"Finished in {time.time() - started:.1f}s")
            return
        print(f"[CACHE] signature mismatch (cached={cached_sig}, current={signature}); retraining...")

    metric_keys = ("mse_mean", "mae_mean", "r2_mean", "hmse_mean", "qlike_mean")
    rows: list[dict] = []
    # Store a single OOS prediction stream per model_type for DM/bootstraps.
    # For transformers with multi-seed evaluation, we store the first seed's stream.
    pred_streams: dict[str, pd.DataFrame] = {}
    hpo_all_logs: list[dict] = []

    if not args.skip_transformers:
        base_d_model = 64
        base_d_ff = 256
        base_n_heads = 4
        base_dropout = 0.2
        seq_len = 240
        patch_size = 12
        n_enc_layers = 3
        n_dec_layers = 2
        n_horizons = len(cfg.train.target_columns)

        for arch_idx, model_type in enumerate(architectures, start=1):
            print("\n" + "=" * 90)
            print(f"[ARCH {arch_idx}/{len(architectures)}] {model_type} | seeds={seeds}")
            print("=" * 90)

            # 1) Decide d_model / d_ff (matched-params or defaults)
            if target_params is not None:
                best_d, matched_n = _find_dmodel_for_target_params(
                    target_params=target_params,
                    model_type=model_type,
                    input_dim=input_dim,
                    seq_len=seq_len, patch_size=patch_size,
                    n_heads=base_n_heads,
                    n_enc_layers=n_enc_layers, n_dec_layers=n_dec_layers,
                    n_horizons=n_horizons, dropout=base_dropout,
                )
                arch_d_model = best_d
                arch_d_ff = 4 * best_d
                print(
                    f"  [MATCH] target={target_params:,} -> d_model={arch_d_model} "
                    f"d_ff={arch_d_ff} params={matched_n:,}"
                )
            else:
                arch_d_model = base_d_model
                arch_d_ff = base_d_ff

            # Build base model_cfg for this architecture.
            arch_model_cfg: ModelConfig = replace(
                cfg.model,
                model_type=model_type,
                d_model=arch_d_model,
                n_heads=base_n_heads,
                d_ff=arch_d_ff,
                dropout=base_dropout,
                seq_len=seq_len,
                patch_size=patch_size,
                n_enc_layers=n_enc_layers,
                n_dec_layers=n_dec_layers,
                n_horizons=n_horizons,
            )

            # 2) HPO (optional)
            final_model_cfg = arch_model_cfg
            final_train_cfg = cfg.train
            if args.hpo_trials and args.hpo_trials > 1 and cfg.train.max_epochs >= 3:
                print(f"  [HPO] random search | trials={args.hpo_trials} | seed={seeds[0]}")
                best_hp, trial_logs = _hpo_random_search(
                    args=args,
                    model_type=model_type,
                    model_cfg=arch_model_cfg,
                    train_cfg=cfg.train,
                    data_path=cfg.data_path,
                    feature_columns=feature_columns,
                    val_frac=float(args.val_frac),
                    seed=int(seeds[0]),
                    n_trials=int(args.hpo_trials),
                )
                hpo_all_logs.extend(trial_logs)
                final_model_cfg = replace(arch_model_cfg, dropout=float(best_hp["dropout"]))
                final_train_cfg = replace(
                    cfg.train,
                    lr=float(best_hp["lr"]),
                    weight_decay=float(best_hp["weight_decay"]),
                )
                print(
                    f"  [HPO BEST] lr={best_hp['lr']:.2e} do={best_hp['dropout']:.2f} "
                    f"wd={best_hp['weight_decay']:.2e}"
                )

            # 3) Count params for final config
            n_params = _count_model_params(
                model_type=model_type,
                input_dim=input_dim,
                seq_len=seq_len, patch_size=patch_size,
                d_model=final_model_cfg.d_model, n_heads=final_model_cfg.n_heads,
                n_enc_layers=final_model_cfg.n_enc_layers,
                n_dec_layers=final_model_cfg.n_dec_layers,
                d_ff=final_model_cfg.d_ff,
                n_horizons=n_horizons, dropout=final_model_cfg.dropout,
            )

            # 4) Train across seeds
            arch_started = time.time()
            per_run_metrics: list[dict] = []
            for seed in seeds:
                seed_started = time.time()
                train_cfg_s = replace(final_train_cfg, seed=int(seed))
                result = train_walk_forward_regression(
                    data_path=cfg.data_path,
                    features_path="",
                    model_cfg=final_model_cfg,
                    train_cfg=train_cfg_s,
                    save_models=False,
                    model_prefix=f"{model_type}_fold",
                    run_name=f"arch_{model_type}_seed{seed}",
                    val_frac=float(args.val_frac),
                    feature_columns=feature_columns,
                )
                fold_metrics = result["metrics_per_fold"]
                per_run_metrics.extend(fold_metrics)
                if seed == seeds[0] and "predictions_df" in result and isinstance(result["predictions_df"], pd.DataFrame):
                    pred_streams[model_type] = result["predictions_df"].copy()
                mse_seed = float(np.nanmean([m.get("mse_mean", np.nan) for m in fold_metrics]))
                qlike_seed = float(np.nanmean([m.get("qlike_mean", np.nan) for m in fold_metrics]))
                print(
                    f"  [seed={seed}] mse={mse_seed:.6f} qlike={qlike_seed:.6f} "
                    f"elapsed={time.time() - seed_started:.1f}s"
                )

            # 5) Cost / throughput measurement
            cost = _measure_cost(
                model_type=model_type, device=device, input_dim=input_dim,
                seq_len=seq_len, patch_size=patch_size,
                d_model=final_model_cfg.d_model, n_heads=final_model_cfg.n_heads,
                n_enc_layers=final_model_cfg.n_enc_layers,
                n_dec_layers=final_model_cfg.n_dec_layers,
                d_ff=final_model_cfg.d_ff,
                n_horizons=n_horizons, dropout=final_model_cfg.dropout,
                batch_size=int(args.cost_batch_size), n_iter=int(args.cost_iters),
            )

            row: dict = {
                "model_type": model_type,
                "n_params": n_params,
                "n_seeds": len(seeds),
                "n_folds": cfg.train.n_splits,
                "n_samples": len(per_run_metrics),
                "device": device.type,
                "elapsed_sec": round(time.time() - arch_started, 2),
            }
            row.update({
                "latency_ms_batch": cost["latency_ms_batch"],
                "latency_ms_sample": cost["latency_ms_sample"],
                "throughput_samples_per_sec": cost["throughput_samples_per_sec"],
                "peak_mem_mb": cost["peak_mem_mb"],
                "cost_batch_size": cost["cost_batch_size"],
            })
            for key in metric_keys:
                mean, std = _aggregate_metric(per_run_metrics, key)
                row[key] = mean
                row[key.replace("_mean", "_std")] = std
            row["model_config"] = json.dumps(asdict(final_model_cfg), ensure_ascii=False)
            rows.append(row)
            print(
                f"[ARCH DONE] {model_type}: params={n_params:,} "
                f"mse={row['mse_mean']:.6f}+-{row['mse_std']:.6f} "
                f"qlike={row['qlike_mean']:.6f}+-{row['qlike_std']:.6f} "
                f"lat_batch={cost['latency_ms_batch']:.2f}ms "
                f"peak_mem={cost['peak_mem_mb']:.1f}MB "
                f"elapsed={row['elapsed_sec']}s"
            )

    if not args.skip_baselines:
        # Also capture baseline OOS prediction streams for DM/bootstraps.
        baseline_rows = _run_baselines_block(
            data_path=cfg.data_path,
            n_splits=cfg.train.n_splits,
            target_columns=cfg.train.target_columns,
            metric_keys=metric_keys,
            project_root=project_root,
        )
        rows.extend(baseline_rows)

        # Re-run baselines with return_predictions=True for the DM streams
        # (cheap compared to transformers; required for aligned per-timestamp losses).
        baselines_dir = os.path.join(project_root, "baselines")
        if baselines_dir not in sys.path:
            sys.path.insert(0, baselines_dir)
        from historical_mean_baseline import run as run_hist  # type: ignore
        from har_rv_baseline import run as run_har_rv  # type: ignore
        from har_rv_j_baseline import run as run_har_rv_j  # type: ignore
        from lightgbm_baseline import run as run_lgbm  # type: ignore
        from linear_regression_baseline import run as run_lin  # type: ignore
        from lstm_baseline import run as run_lstm  # type: ignore
        from persistence_baseline import run as run_pers  # type: ignore

        baseline_specs = [
            ("baseline:persistence", run_pers),
            ("baseline:historical_mean", run_hist),
            ("baseline:har_rv", run_har_rv),
            ("baseline:har_rv_j", run_har_rv_j),
            ("baseline:linear_ridge", run_lin),
            ("baseline:lightgbm", run_lgbm),
        ]
        if not args.skip_lstm_baseline:
            baseline_specs.append(("baseline:lstm", run_lstm))
        for name, fn in baseline_specs:
            try:
                out = fn(
                    data_path=cfg.data_path,
                    n_splits=cfg.train.n_splits,
                    target_columns=cfg.train.target_columns,
                    return_predictions=True,
                )
                if isinstance(out, dict) and isinstance(out.get("predictions_df"), pd.DataFrame):
                    pred_streams[name] = out["predictions_df"].copy()
            except Exception:
                continue

    if not rows:
        print("[WARN] No rows produced (everything skipped?).")
        return

    # Primary ranking metric for RV experiments is QLIKE (lower is better).
    # Keep MSE as tie-breaker to preserve additional signal.
    summary = (
        pd.DataFrame(rows)
        .sort_values(["qlike_mean", "mse_mean"], ascending=[True, True])
        .reset_index(drop=True)
    )

    # DM-test + block bootstrap (per-horizon + aggregate) vs reference model.
    ref = str(args.dm_ref).strip()
    if ref in pred_streams:
        n_boot = int(args.dm_n_boot)
        if args.quick:
            n_boot = min(n_boot, 200)
        hac_lags = int(args.dm_block_size) - 1
        _append_text(
            dm_log_path,
            (
                "\n" + "=" * 110 + "\n"
                f"[TS   ] {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
                f"[SYMB ] {symbol}\n"
                f"[REF  ] {ref}\n"
                f"[CSV  ] {out_csv}\n"
                f"[CONF ] block_size={int(args.dm_block_size)} n_boot={n_boot} hac_lags={hac_lags}\n"
                + "-" * 110 + "\n"
            ),
        )
        for i in range(len(summary)):
            mt = str(summary.loc[i, "model_type"])
            if mt == ref:
                continue
            if mt not in pred_streams:
                continue
            stats = _compute_dm_and_bootstrap(
                pred_m0=pred_streams[mt],
                pred_m1=pred_streams[ref],
                target_columns=cfg.train.target_columns,
                block_size=int(args.dm_block_size),
                n_boot=n_boot,
                hac_lags=hac_lags,
                seed=42,
            )
            for k, v in stats.items():
                summary.loc[i, k] = v
            # Full DM/CI columns are stored in the CSV; keep this log lightweight.
            p_agg = float(stats.get("dm_p_agg", float("nan")))
            d_agg = float(stats.get("diff_mean_agg", float("nan")))
            _append_text(
                dm_log_path,
                f"[DM ] {mt:28s} vs {ref:16s} | dm_p_agg={p_agg:.6g} diff_mean_agg={d_agg:.6g}\n",
            )
        summary.loc[summary["model_type"] == ref, "dm_ref"] = ref
        _append_text(dm_log_path, "-" * 110 + "\n")
    else:
        print(f"[WARN] DM/bootstraps skipped: reference model '{ref}' has no prediction stream.")
    summary.to_csv(out_csv, index=False)
    with open(sig_path, "w", encoding="utf-8") as f:
        json.dump({"signature": signature, "payload": signature_payload}, f, ensure_ascii=False, indent=2)
    if hpo_all_logs:
        pd.DataFrame(hpo_all_logs).to_csv(hpo_csv, index=False)
        print(f"[HPO] Saved trial log: {hpo_csv}")

    _progress(2, 3, f"Saved results to {out_csv}")
    print("\n" + "=" * 110)
    print("  UNIFIED COMPARISON SUMMARY (transformers + baselines)")
    print("=" * 110)
    display_cols = [
        "model_type", "n_params",
        "mse_mean", "mse_std", "qlike_mean", "qlike_std",
        "mae_mean", "r2_mean", "da_mean",
        "latency_ms_batch", "peak_mem_mb",
        "n_seeds", "n_folds", "elapsed_sec",
    ]
    display_cols = [c for c in display_cols if c in summary.columns]
    print(summary[display_cols].to_string(index=False))
    _progress(3, 3, f"Finished in {time.time() - started:.1f}s")


if __name__ == "__main__":
    main()
