"""
Statistical tests for model-comparison on time-series loss streams.

Implements:
- QLIKE loss series (per timestamp)
- Moving-block bootstrap confidence intervals for mean(loss) / mean(diff)
- Diebold–Mariano test with HAC (Newey–West) standard errors

This module is designed to operate on out-of-sample prediction streams
generated by the walk-forward pipeline: aligned sequences of (y_true, y_pred).
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Literal

import numpy as np


def qlike_series(y_true: np.ndarray, y_pred: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    """Compute per-sample QLIKE loss series: log(v_hat) + v / v_hat."""
    yt = np.clip(np.asarray(y_true, dtype=float), eps, None)
    yp = np.clip(np.asarray(y_pred, dtype=float), eps, None)
    return np.log(yp) + yt / yp


def _moving_block_indices(n: int, block_size: int, rng: np.random.Generator) -> np.ndarray:
    """Sample indices [0..n) using moving-block bootstrap."""
    if n <= 0:
        return np.empty((0,), dtype=np.int64)
    b = int(block_size)
    if b <= 0:
        raise ValueError("block_size must be > 0")
    if b > n:
        b = n
    starts = rng.integers(0, n - b + 1, size=int(np.ceil(n / b)), endpoint=False)
    idx = np.concatenate([np.arange(s, s + b, dtype=np.int64) for s in starts], axis=0)
    return idx[:n]


def moving_block_bootstrap_mean_ci(
    series: np.ndarray,
    *,
    block_size: int = 48,
    n_boot: int = 2000,
    alpha: float = 0.05,
    rng: np.random.Generator | None = None,
) -> tuple[float, float, float]:
    """Percentile CI for mean(series) via moving-block bootstrap."""
    x = np.asarray(series, dtype=float)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return float("nan"), float("nan"), float("nan")
    if rng is None:
        rng = np.random.default_rng(42)
    n = int(x.size)
    means = np.empty(int(n_boot), dtype=np.float64)
    for i in range(int(n_boot)):
        idx = _moving_block_indices(n, block_size, rng)
        means[i] = float(np.mean(x[idx]))
    mean = float(np.mean(x))
    lo = float(np.quantile(means, alpha / 2.0))
    hi = float(np.quantile(means, 1.0 - alpha / 2.0))
    return mean, lo, hi


def _hac_long_run_variance(d: np.ndarray, lags: int) -> float:
    """HAC long-run variance estimate with Bartlett weights."""
    x = np.asarray(d, dtype=float)
    x = x[np.isfinite(x)]
    n = int(x.size)
    if n <= 1:
        return float("nan")
    x = x - float(np.mean(x))
    L = int(max(0, lags))
    if L == 0:
        return float(np.mean(x * x))

    gamma0 = float(np.mean(x * x))
    lrv = gamma0
    for k in range(1, min(L, n - 1) + 1):
        w = 1.0 - (k / (L + 1.0))
        cov = float(np.mean(x[k:] * x[:-k]))
        lrv += 2.0 * w * cov
    return float(max(lrv, 1e-18))


@dataclass(frozen=True)
class DMResult:
    dm_stat: float
    p_value: float
    mean_diff: float
    se: float
    n: int
    hac_lags: int


def _normal_cdf(z: float) -> float:
    # Approximate CDF via error function; avoids scipy dependency.
    return 0.5 * (1.0 + float(math.erf(z / math.sqrt(2.0))))


def dm_test(
    loss_m0: np.ndarray,
    loss_m1: np.ndarray,
    *,
    hac_lags: int | None = None,
    alternative: Literal["two-sided", "less", "greater"] = "two-sided",
) -> DMResult:
    """Diebold–Mariano test for equal predictive accuracy.

    We test E[d_t] = 0 where d_t = loss_m0 - loss_m1.
    Positive mean_diff => model1 better (lower loss).
    """
    a = np.asarray(loss_m0, dtype=float)
    b = np.asarray(loss_m1, dtype=float)
    if a.shape != b.shape:
        raise ValueError(f"loss streams must have same shape, got {a.shape} vs {b.shape}")
    mask = np.isfinite(a) & np.isfinite(b)
    d = (a[mask] - b[mask]).astype(float)
    n = int(d.size)
    if n <= 1:
        return DMResult(float("nan"), float("nan"), float("nan"), float("nan"), n, int(hac_lags or 0))

    mean_diff = float(np.mean(d))
    if hac_lags is None:
        # Standard heuristic.
        hac_lags = int(np.floor(n ** (1.0 / 3.0)))
    lrv = _hac_long_run_variance(d, int(hac_lags))
    se = float(np.sqrt(lrv / n))
    dm = float(mean_diff / se) if se > 0 else float("nan")

    # Normal-approx p-value.
    if not np.isfinite(dm):
        p = float("nan")
    else:
        if alternative == "two-sided":
            p = 2.0 * (1.0 - _normal_cdf(abs(dm)))
        elif alternative == "greater":
            # H1: mean_diff > 0
            p = 1.0 - _normal_cdf(dm)
        elif alternative == "less":
            # H1: mean_diff < 0
            p = _normal_cdf(dm)
        else:
            raise ValueError(f"Unknown alternative: {alternative}")

    return DMResult(
        dm_stat=dm,
        p_value=float(p),
        mean_diff=mean_diff,
        se=se,
        n=n,
        hac_lags=int(hac_lags),
    )

